name:  Deploying kc-pit-2026 branch to rds-main (rob) slot

on:
  push:
    branches:
      - kc-pit-2026 # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v6

      # Setup Node.js (adjust version as needed)
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"

      # Install client and server dependencies and build React app
      - name: Install client dependencies
        run: |
          cd client
          npm install

      - name: Build React client
        run: |
          cd client
          npm run build

      # Copy React dist into server folder
      - name: Copy React dist to server build folder
        run: |
          rm -rf server/dist
          cp -r client/dist server/dist

      # Install server dependencies
      - name: Install server dependencies
        run: |
          cd server
          npm install

      # Build server dependencies
      - name: Build server
        run: |
          cd server
          npm run build

      # Deploy to Azure App Service using Azure/webapps-deploy action
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: rds-main # Replace with your Azure App Service name
          slot-name: "Production"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_rds_main_rob }}
          package: ./server
